name: test-state_machine_cpp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" -DCOMPILE_TESTS=ON ..
      - name: make
        run: cd build && make
      - name: Run Test
        run: cd build/tests && ./test_state_machine_cpp